name: PyTest

on: [push]

jobs:
  test:
    runs-on: windows
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      run: pytest

    - name: Build and deploy
      run: pytest main.py
